name: food_recognizer_app
description: Food Recognizer App
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # CAMERA & IMAGE
  image_picker: ^1.1.2
  image_cropper: ^7.1.0
  camera: ^0.11.0
  permission_handler: ^11.3.1

  # MACHINE LEARNING
  tflite_flutter: ^0.11.0

  # FIREBASE (FIXED)
  firebase_core: ^2.32.0
  firebase_ml_model_downloader: ^0.2.0

  # API
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

