// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDM9FODsOGdKWg-rRISlBxSni3DmXX3IpY',
    appId: '1:268764379138:web:5a1bcf54594b298bfccf1b',
    messagingSenderId: '268764379138',
    projectId: 'food-recognizer-4dff0',
    authDomain: 'food-recognizer-4dff0.firebaseapp.com',
    storageBucket: 'food-recognizer-4dff0.firebasestorage.app',
    measurementId: 'G-R9B6NGD5HR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAidTVPgPiDBFj1zjyod-n_sawEPnzjcyI',
    appId: '1:268764379138:android:04609ed8da476f78fccf1b',
    messagingSenderId: '268764379138',
    projectId: 'food-recognizer-4dff0',
    storageBucket: 'food-recognizer-4dff0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyeb8WxL-vZNkeaLzyjmOCyGGTj-y17c4',
    appId: '1:268764379138:ios:ec1289324e8ad2b5fccf1b',
    messagingSenderId: '268764379138',
    projectId: 'food-recognizer-4dff0',
    storageBucket: 'food-recognizer-4dff0.firebasestorage.app',
    iosBundleId: 'com.example.foodRecognier',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyeb8WxL-vZNkeaLzyjmOCyGGTj-y17c4',
    appId: '1:268764379138:ios:ec1289324e8ad2b5fccf1b',
    messagingSenderId: '268764379138',
    projectId: 'food-recognizer-4dff0',
    storageBucket: 'food-recognizer-4dff0.firebasestorage.app',
    iosBundleId: 'com.example.foodRecognier',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDM9FODsOGdKWg-rRISlBxSni3DmXX3IpY',
    appId: '1:268764379138:web:bef6b6fb2ba66182fccf1b',
    messagingSenderId: '268764379138',
    projectId: 'food-recognizer-4dff0',
    authDomain: 'food-recognizer-4dff0.firebaseapp.com',
    storageBucket: 'food-recognizer-4dff0.firebasestorage.app',
    measurementId: 'G-NQNJVMEP35',
  );
}
